@echo off
mkdir countries
cd countries

(
echo Aruba
echo Afghanistan
echo Angola
echo Anguilla
echo landIslands
echo Albania
echo Andorra
echo UnitedArabEmirates
echo Argentina
echo Armenia
echo AmericanSamoa
echo Antarctica
echo FrenchSouthernTerritories
echo AntiguaandBarbuda
echo Australia
echo Austria
echo Azerbaijan
echo Burundi
echo Belgium
echo Benin
echo BonaireSintEustatiusandSaba
echo BurkinaFaso
echo Bangladesh
echo Bulgaria
echo Bahrain
echo Bahamas
echo BosniaandHerzegovina
echo SaintBarthlemy
echo Belarus
echo Belize
echo Bermuda
echo BoliviaPlurinationalStateof
echo Brazil
echo Barbados
echo BruneiDarussalam
echo Bhutan
echo BouvetIsland
echo Botswana
echo CentralAfricanRepublic
echo Canada
echo CocosKeelingIslands
echo Switzerland
echo Chile
echo China
echo CtedIvoire
echo Cameroon
echo CongoTheDemocraticRepublicofthe
echo Congo
echo CookIslands
echo Colombia
echo Comoros
echo CaboVerde
echo CostaRica
echo Cuba
echo Curaao
echo ChristmasIsland
echo CaymanIslands
echo Cyprus
echo Czechia
echo Germany
echo Djibouti
echo Dominica
echo Denmark
echo DominicanRepublic
echo Algeria
echo Ecuador
echo Egypt
echo Eritrea
echo WesternSahara
echo Spain
echo Estonia
echo Ethiopia
echo Finland
echo Fiji
echo FalklandIslandsMalvinas
echo France
echo FaroeIslands
echo MicronesiaFederatedStatesof
echo Gabon
echo UnitedKingdom
echo Georgia
echo Guernsey
echo Ghana
echo Gibraltar
echo Guinea
echo Guadeloupe
echo Gambia
echo GuineaBissau
echo EquatorialGuinea
echo Greece
echo Grenada
echo Greenland
echo Guatemala
echo FrenchGuiana
echo Guam
echo Guyana
echo HongKong
echo HeardIslandandMcDonaldIslands
echo Honduras
echo Croatia
echo Haiti
echo Hungary
echo Indonesia
echo IsleofMan
echo India
echo BritishIndianOceanTerritory
echo Ireland
echo IranIslamicRepublicof
echo Iraq
echo Iceland
echo Israel
echo Italy
echo Jamaica
echo Jersey
echo Jordan
echo Japan
echo Kazakhstan
echo Kenya
echo Kyrgyzstan
echo Cambodia
echo Kiribati
echo SaintKittsandNevis
echo KoreaRepublicof
echo Kuwait
echo LaoPeoplesDemocraticRepublic
echo Lebanon
echo Liberia
echo Libya
echo SaintLucia
echo Liechtenstein
echo SriLanka
echo Lesotho
echo Lithuania
echo Luxembourg
echo Latvia
echo Macao
echo SaintMartinFrenchpart
echo Morocco
echo Monaco
echo MoldovaRepublicof
echo Madagascar
echo Maldives
echo Mexico
echo MarshallIslands
echo NorthMacedonia
echo Mali
echo Malta
echo Myanmar
echo Montenegro
echo Mongolia
echo NorthernMarianaIslands
echo Mozambique
echo Mauritania
echo Montserrat
echo Martinique
echo Mauritius
echo Malawi
echo Malaysia
echo Mayotte
echo Namibia
echo NewCaledonia
echo Niger
echo NorfolkIsland
echo Nigeria
echo Nicaragua
echo Niue
echo Netherlands
echo Norway
echo Nepal
echo Nauru
echo NewZealand
echo Oman
echo Pakistan
echo Panama
echo Pitcairn
echo Peru
echo Philippines
echo Palau
echo PapuaNewGuinea
echo Poland
echo PuertoRico
echo KoreaDemocraticPeoplesRepublicof
echo Portugal
echo Paraguay
echo PalestineStateof
echo FrenchPolynesia
echo Qatar
echo Runion
echo Romania
echo RussianFederation
echo Rwanda
echo SaudiArabia
echo Sudan
echo Senegal
echo Singapore
echo SouthGeorgiaandtheSouthSandwichIslands
echo SaintHelenaAscensionandTristandaCunha
echo SvalbardandJanMayen
echo SolomonIslands
echo SierraLeone
echo ElSalvador
echo SanMarino
echo Somalia
echo SaintPierreandMiquelon
echo Serbia
echo SouthSudan
echo SaoTomeandPrincipe
echo Suriname
echo Slovakia
echo Slovenia
echo Sweden
echo Eswatini
echo SintMaartenDutchpart
echo Seychelles
echo SyrianArabRepublic
echo TurksandCaicosIslands
echo Chad
echo Togo
echo Thailand
echo Tajikistan
echo Tokelau
echo Turkmenistan
echo TimorLeste
echo Tonga
echo TrinidadandTobago
echo Tunisia
echo Turkey
echo Tuvalu
echo TaiwanProvinceofChina
echo TanzaniaUnitedRepublicof
echo Uganda
echo Ukraine
echo UnitedStatesMinorOutlyingIslands
echo Uruguay
echo UnitedStates
echo Uzbekistan
echo HolySeeVaticanCityState
echo SaintVincentandtheGrenadines
echo VenezuelaBolivarianRepublicof
echo VirginIslandsBritish
echo VirginIslandsUS
echo VietNam
echo Vanuatu
echo WallisandFutuna
echo Samoa
echo Yemen
echo SouthAfrica
echo Zambia
echo Zimbabwe
) > country_list.txt

for /f "delims=" %%c in (country_list.txt) do (
    type nul > "%%c.html"
)

del country_list.txt
echo Done! %cd%
